name: Release new version

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test case
      run: xcodebuild test -workspace Example/CleanJSON.xcworkspace -scheme CleanJSON_Tests -destination 'platform=iOS Simulator,name=iPhone 11'
    - name: Install cocoapods
      run: gem install cocoapods --pre && pod install --project-directory=Example
    - name: Release
      run: pod trunk push --allow-warnings
