name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: xcodebuild test -workspace Example/CleanJSON.xcworkspace -scheme CleanJSON_Tests -destination 'platform=iOS Simulator,name=iPhone 11'
    - name: Install cocoapods
      run: gem install cocoapods --pre && pod install --project-directory=Example
    - name: Pod lib lint
      run: pod lib lint --allow-warnings
